#!/usr/bin/env bash
if ! [ "$1" ]; then
  echo "error: missing database name"
  exit 1
fi
name=$1
exec docker run \
  -p 3306:3306 \
  -v $HOME/volatile/db/mysql-$name:/var/lib/mysql \
  --name mysql-$name \
  -e MYSQL_DATABASE=$name \
  -e MYSQL_USER=$name \
  -e MYSQL_PASSWORD=$name \
  -e MYSQL_RANDOM_ROOT_PASSWORD=1 mariadb
